#!/usr/bin/env python3
"""Fix broken template literals in the HTTP register route."""

with open('/workspaces/Toolkit/artifacts/api-server/src/routes/tools.ts', 'r') as f:
    content = f.read()

# Find and replace the broken HTTP route section
old_start = '// ── Cursor HTTP 注册（无浏览器，纯 HTTP 协议）────────────────────────────────'
old_end   = 'router.get("/tools/ip-check"'

si = content.find(old_start)
ei = content.find(old_end)
assert si != -1, 'start marker not found'
assert ei != -1, 'end marker not found'

# Build correct route using Python strings (no bash expansion risk)
backtick = '`'
dollar   = '$'

new_route = (
    '// ── Cursor HTTP 注册（无浏览器，纯 HTTP 协议）────────────────────────────────\n'
    '// POST /tools/cursor/register-http\n'
    'router.post("/tools/cursor/register-http", async (req, res) => {\n'
    '  const {\n'
    '    email = "",\n'
    '    password = "",\n'
    '    proxy: proxyInput = "",\n'
    '    useXray = false,\n'
    '    skipStep1 = false,\n'
    '    autoProxy = false,\n'
    '    captchaService = "yescaptcha",\n'
    '    captchaKey = "",\n'
    '    imapHost = "",\n'
    '    imapUser = "",\n'
    '    imapPass = "",\n'
    '    outlookAccountId,\n'
    '  } = req.body as {\n'
    '    email?: string; password?: string; proxy?: string;\n'
    '    useXray?: boolean; skipStep1?: boolean; autoProxy?: boolean;\n'
    '    captchaService?: string; captchaKey?: string;\n'
    '    imapHost?: string; imapUser?: string; imapPass?: string;\n'
    '    outlookAccountId?: number;\n'
    '  };\n\n'
    '  let proxy = proxyInput;\n'
    '  if (useXray) {\n'
    '    proxy = "socks5://127.0.0.1:10808";\n'
    '  } else if (!proxy && autoProxy) {\n'
    '    try {\n'
    '      const { query: dbQuery } = await import("../db.js");\n'
    '      const rows = await dbQuery<{ formatted: string }>(\n'
    '        "SELECT formatted FROM proxies WHERE status != \'banned\' ORDER BY used_count ASC, RANDOM() LIMIT 1"\n'
    '      );\n'
    '      if (rows[0]) proxy = rows[0].formatted;\n'
    '    } catch {}\n'
    '  }\n\n'
    '  let resolvedEmail = email;\n'
    '  let resolvedImapUser = imapUser;\n'
    '  let resolvedImapPass = imapPass;\n'
    '  if (outlookAccountId) {\n'
    '    try {\n'
    '      const { query: dbQuery } = await import("../db.js");\n'
    '      const rows = await dbQuery<{ email: string; password: string | null }>(\n'
    '        "SELECT email, password FROM accounts WHERE id=$1 AND platform=\'outlook\'",\n'
    '        [outlookAccountId]\n'
    '      );\n'
    '      if (rows[0]) {\n'
    '        resolvedEmail = resolvedEmail || rows[0].email;\n'
    '        if (!resolvedImapUser) resolvedImapUser = rows[0].email;\n'
    '        if (!resolvedImapPass) resolvedImapPass = rows[0].password ?? "";\n'
    '      }\n'
    '    } catch {}\n'
    '  }\n\n'
    + f'  const jobId = {backtick}curhttp_{dollar}{{Date.now()}}_{dollar}{{Math.random().toString(36).slice(2, 8)}}{backtick};\n'
    + '  const job = await jobQueue.create(jobId);\n'
    '  const proxyDisplay = proxy ? proxy.replace(/:([^:@]{4})[^:@]*@/, ":****@") : "无代理";\n'
    + f'  job.logs.push({{ type: "start", message: {backtick}启动 Cursor HTTP 注册（纯 HTTP，无浏览器）...{backtick} }});\n'
    + f'  if (proxy) job.logs.push({{ type: "log", message: {backtick}🌐 代理: {dollar}{{proxyDisplay}}{backtick} }});\n'
    + '  if (skipStep1) job.logs.push({ type: "log", message: "⏭️  跳过 Step1（直接 Server Action）" });\n\n'
    '  res.json({ success: true, jobId, message: "Cursor HTTP 注册任务已启动" });\n\n'
    '  const { spawn } = await import("child_process");\n'
    '  const scriptPath = new URL("../cursor_register_http.py", import.meta.url).pathname;\n'
    '  const args = [scriptPath];\n'
    '  if (resolvedEmail)   args.push("--email", resolvedEmail);\n'
    '  if (password)        args.push("--password", password);\n'
    '  if (proxy)           args.push("--proxy", proxy);\n'
    '  if (useXray)         args.push("--use-xray");\n'
    '  if (skipStep1)       args.push("--skip-step1");\n'
    '  if (captchaService)  args.push("--captcha-service", captchaService);\n'
    '  if (captchaKey)      args.push("--captcha-key", captchaKey);\n'
    '  if (imapHost || resolvedImapUser) {\n'
    '    args.push("--imap-host",  imapHost || "outlook.office365.com");\n'
    '    args.push("--imap-user",  resolvedImapUser);\n'
    '    args.push("--imap-pass",  resolvedImapPass);\n'
    '  }\n\n'
    '  const child = spawn("python3", args, { env: { ...process.env, PYTHONUNBUFFERED: "1" } });\n'
    '  jobQueue.setChild(jobId, child);\n\n'
    '  child.stdout.on("data", (chunk: Buffer) => {\n'
    '    for (const line of chunk.toString().split("\\n")) {\n'
    '      const s = line.trim();\n'
    '      if (!s) continue;\n'
    '      try {\n'
    '        const ev = JSON.parse(s);\n'
    '        if (ev.success === true && ev.token) {\n'
    '          job.accounts.push({ email: ev.email, password: ev.password, token: ev.token });\n'
    + f'          job.logs.push({{ type: "success", message: {backtick}✅ 注册成功: {dollar}{{ev.email}} | token {dollar}{{ev.token.length}} chars{backtick} }});\n'
    '          import("../db.js").then(({ execute: dbExec }) => {\n'
    '            dbExec(\n'
    "              `INSERT INTO accounts (platform, email, password, token, status, notes, created_at)\n"
    "               VALUES ('cursor', $1, $2, $3, 'active', 'HTTP注册', NOW())\n"
    "               ON CONFLICT (platform, email) DO UPDATE\n"
    "                 SET password = EXCLUDED.password, token = EXCLUDED.token, status = 'active'`,\n"
    '              [ev.email, ev.password, ev.token]\n'
    '            ).catch(() => {});\n'
    '          }).catch(() => {});\n'
    '          return;\n'
    '        }\n'
    '        if (ev.success === false && ev.error) {\n'
    + f'          job.logs.push({{ type: "error", message: {backtick}❌ {dollar}{{ev.error}}{backtick} }});\n'
    '          return;\n'
    '        }\n'
    '      } catch {}\n'
    '      const isErr = /error|Error|failed|失败|异常/.test(s) && !/Step.*->/.test(s);\n'
    '      job.logs.push({ type: isErr ? "error" : "log", message: s });\n'
    '    }\n'
    '  });\n\n'
    '  child.stderr.on("data", (chunk: Buffer) => {\n'
    '    const s = chunk.toString().trim();\n'
    '    if (s && !s.includes("DeprecationWarning") && !s.includes("FutureWarning")) {\n'
    '      job.logs.push({ type: "error", message: s.slice(0, 300) });\n'
    '    }\n'
    '  });\n\n'
    '  child.on("close", async (code) => {\n'
    '    const ok = (job.accounts as unknown[]).length;\n'
    + f'    job.logs.push({{ type: ok ? "done" : "error", message: {backtick}任务结束  成功: {dollar}{{ok}} 个{backtick} }});\n'
    '    await jobQueue.finish(jobId, code ?? -1, ok ? "done" : "failed");\n'
    '  });\n'
    '});\n\n'
    'router.get("/tools/cursor/register-http/:jobId", async (req, res) => {\n'
    '  const job = await jobQueue.get(req.params.jobId);\n'
    '  if (!job) { res.status(404).json({ success: false, error: "任务不存在" }); return; }\n'
    '  const since = Number(req.query.since ?? 0);\n'
    '  res.json({ success: true, status: job.status, accounts: job.accounts, logs: job.logs.slice(since), nextSince: job.logs.length });\n'
    '});\n\n'
    'router.delete("/tools/cursor/register-http/:jobId", (req, res) => {\n'
    '  const stopped = jobQueue.stop(req.params.jobId);\n'
    '  if (!stopped) { res.status(404).json({ success: false }); return; }\n'
    '  res.json({ success: true });\n'
    '});\n\n'
)

content = content[:si] + new_route + content[ei:]

with open('/workspaces/Toolkit/artifacts/api-server/src/routes/tools.ts', 'w') as f:
    f.write(content)

print(f'Done. Total lines: {content.count(chr(10))}')
